services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: company-info-system
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - LOG_LEVEL=DEBUG
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./config:/app/config

  redis:
    image: redis:7.2-alpine
    container_name: company-info-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 20 1 --loglevel warning

  redis-commander:
    image: redislabs/redisinsight:latest
    container_name: redis-commander
    ports:
      - "8081:8001"
    depends_on:
      - redis


volumes:
  redis-data:
